# Generated by Django 5.0.3 on 2024-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='text/')),
                ('slug', models.CharField(default=None, max_length=100, null=True)),
                ('counter_words', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
