# Generated by Django 5.0.3 on 2024-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=1, upload_to='text/'),
            preserve_default=False,
        ),
    ]
