# Generated by Django 5.0.3 on 2024-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='secret_key',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
