# Generated by Django 5.0.3 on 2024-03-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_remove_uploadfile_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='secret_key',
            new_name='slug',
        ),
    ]
