# Generated by Django 5.0.3 on 2024-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_uploadfile_counter_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='counter_words',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
