# Generated by Django 5.0.3 on 2024-03-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(editable=False, max_length=50)),
                ('counter', models.PositiveIntegerField()),
                ('term_frequency', models.FloatField()),
                ('document', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='file.uploadfile')),
            ],
        ),
    ]
