# Generated by Django 5.0.3 on 2024-03-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_uploadfile_secret_key'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordsmodel',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='wordsmodel',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.uploadfile'),
        ),
    ]
