# Generated by Django 5.0.3 on 2024-03-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_remove_wordsmodel_secret_key_wordsmodel_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordsmodel',
            name='document',
        ),
    ]
