# Generated by Django 5.0.3 on 2024-03-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_rename_secret_key_uploadfile_slug'),
        ('words', '0004_wordsmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsmodel',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='file.uploadfile'),
        ),
    ]
